defmodule Counter do
  @moduledoc """
  Documentation for Counter.
  """

  def clear, do: GenServer.cast(Counter.Server, :clear)
  def count, do: GenServer.call(Counter.Server, :count)

  @doc "BAD -- has a race condition!"
  def sync1(:count) do
    Registry.register(Counter, :count, [])
    # BUG - event(s) could be generated by publisher at this point and
    # processed by subscriber after this call returns, resulting in the
    # subscriber determining incorrect state.
    GenServer.call(Server, :count)
  end

  @doc "GOOD -- but not implementable using current Registery"
  def sync2(:count) do
    GenServer.call(Server, {:sync2, :count})
  end
end
